# Generated by Django 5.0.1 on 2024-02-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_alter_proveedor_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_entrada',
            name='descripcion',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='orden_salida',
            name='descripcion',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='descripcion',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='vale',
            name='descripcion',
            field=models.CharField(default='', max_length=400),
        ),
    ]
