# Generated by Django 5.0.1 on 2024-02-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_orden_entrada_descripcion_orden_salida_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalles_solicitud',
            old_name='producto',
            new_name='catalogo',
        ),
    ]
