# Generated by Django 5.0.1 on 2024-02-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_rename_producto_detalles_solicitud_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_solicitud',
            name='catalogo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='materiales.catalogo'),
        ),
    ]
