# Generated by Django 5.0.1 on 2024-02-27 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0007_orden_salida_fecha_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_salida',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='Orden_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='materiales.orden_salida'),
        ),
    ]
