# Generated by Django 5.0.1 on 2024-02-27 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0009_rename_orden_salida_solicitud_orden_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='orden_salida',
        ),
        migrations.AddField(
            model_name='orden_salida',
            name='solicitud',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='materiales.solicitud'),
        ),
    ]
