version: '3.9'

services:
  django:
    build:
      context: .
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    networks:
      inventario_network:
        ipv4_address: 172.21.0.3
    container_name: inventario-django-1
    volumes:
      - staticfiles:/app/staticfiles
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:14.3-alpine
    ports:
      - "5433:5432"
    networks:
      inventario_network:
        ipv4_address: 172.21.0.2
    container_name: inventario-postgres-1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    networks:
      inventario_network:
        ipv4_address: 172.21.0.4
    container_name: inventario-nginx-1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - staticfiles:/app/staticfiles
    depends_on:
      - django

  # prometheus:
  #   image: prom/prometheus:v2.49.1
  #   volumes:
  #     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  #   networks:
  #     - inventario_network
  #   ports:
  #     - 9090:9090

  # node-exporter:
  #   image: prom/node-exporter:v1.7.0
  #   networks:
  #     - inventario_network
  #   ports:
  #     - 9100:9100
  # alert-manager:
  #   image: prom/alertmanager
  #   volumes:
  #     - "./alertmanager.yml:/alertmanager/alertmanager.yml"
  #   networks:
  #     - inventario_network
  #   ports:
  #     - 9093:9093

volumes:
  postgres_data:
  staticfiles:

networks:
  inventario_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1